name: Deploy Flask API to Azure (SCM)

on:
  push:
    branches: ["master"]

env:
  AZURE_WEBAPP_NAME: flask-tokenization-api  
  PYTHON_VERSION: "3.11"                      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies (for tests)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests yet — add pytest/unittest here"
        # pytest tests/

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Deploy to Azure Web App via SCM
      uses: azure/webapps-deploy@v3
      with:
        app-name: "tokenizer"
        package: .
