# .github/workflows/deploy.yml
name: Deploy to Azure App Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 'Create virtual environment'
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: 'Install dependencies'
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Download NLTK data'
      run: |
        source venv/bin/activate
        python -c "
        import nltk
        import ssl
        try:
            _create_unverified_https_context = ssl._create_unverified_context
        except AttributeError:
            pass
        else:
            ssl._create_default_https_context = _create_unverified_https_context
        nltk.download('punkt', quiet=True)
        nltk.download('punkt_tab', quiet=True)  
        nltk.download('stopwords', quiet=True)
        nltk.download('averaged_perceptron_tagger', quiet=True)
        print('NLTK data downloaded successfully')
        "
        
    - name: 'Create deployment package'
      run: |
        # Remove virtual environment from deployment package
        rm -rf venv
        # Create a clean package
        zip -r deployment-package.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*venv*" "*.env*"
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment-package.zip